### ISSUE TITLE
Gesammelte Fragen

### ISSUE THREAD

**Issue by RWetenkamp** [Ciolv/SE2-Civilian#3]
**Für Mittwoch, 04.05.2022**
| Nr  |Frage												| Antwort						|
|-----------|-----------------------------------------------------------------------------------------|-------------------------------------------------------------|
|1    | Soll das Projekt eine GUI besitzen? | |
|2   | Gibt es noch weitere Informationen zu den User Stories? ||
| 3 | Müssen wir die Funktionalitäten der Zivilpersonen erweitern? ||
|4   | Wie sieht die Interaktion mit den anderen Teams aus? ||
|5  | Umfasst das Zeimanagement / die agile Arbeitweise nur das eigene Team oder alle beteiligten Teams? ||
|6 | Wie messen wir die Effizienz der Zivilpersonen? ||
|7 | Wie detailiert müssen wir die Userstories zu den Zivilpersonen ausformulieren? (jeden Schritt? / nur bestimmte?) ||
| 8 | Worin unterscheiden sich Zivilpersonen und Flughafenmitarbeitende? (im Code?) ||

**Comment by Ciolv** [comment]
1. Vorschlag: Positionsdaten mit durchgeführter Aktion in Log/Textdatei ausgeben. Keine eigene GUI notwendig.
2. Ja, siehe [Workshop](https://github.com/Ciolv/SE2-Civilian/wiki/Gespr%C3%A4chsprotokoll-des-Workshops-am-04.05.2022).
3. Ebenfalls [Workshop](https://github.com/Ciolv/SE2-Civilian/wiki/Gespr%C3%A4chsprotokoll-des-Workshops-am-04.05.2022).

**Comment by Ciolv** [comment]
4. Abstimmungen mit anderen selbst organisieren, es darf mit allen außer der Angreifer  Gruppe kommuniziert werden.
5. Agile Arbeitsweise bezogen auf die Eigene Gruppe. Dozent dient gerne als Moderator für Retrospektive. Die Adaptionen sollten in der Präsentation dargelegt werden (z.B. kein Daily)
6. Effizienz durch Verzögerung messen (Zeit bis zum Boarding), wie viel Personalaufwand gab es hierfür. 
7. So wie es für uns ausreichend ist um die Aufgabe zu verstehen. 
8. Selbst untersuchen.

Ergebnisse sind im [Wiki](https://github.com/Ciolv/SE2-Civilian/wiki/Vorbereitung-f%C3%BCr-Mittwoch%2C-04.05.2022/_edit).
